apiVersion: v1
kind: Pod
metadata:
  name: back-pod
  labels:
    app: back-pod
spec:
  containers:
  - name: back-app
    image: mehdijebali/crud-back:1.3.1
    env:
      - name: DATABASE_HOST
        valueFrom:
          configMapKeyRef:
            name: back-configmap
            key: databasehost
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"