apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: back-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-pod
  template:
    metadata:
      labels:
        app: back-pod
