apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: database-pod
spec:
  containers:
    - name: database-app
      image: mysql:latest
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"