apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-app
  template:
    metadata:
      labels:
        app: database-app
    spec:
      containers:
    - name: mysql-container
      image: mysql:latest
      env:
      - name: MYSQL_DATABASE
        valueFrom:
          configMapKeyRef:
            name: database-configmap
            key: database
      - name: MYSQL_USER
        valueFrom:
          configMapKeyRef:
            name: database-configmap
            key: user
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: database-secret
            key: rootpassword 
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: database-secret
            key: dbpassword 
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"