apiVersion: v1
kind: Pod
metadata:
  name: front-pod
  labels:
    app: front-pod
spec:
  containers:
    - name: front-app
      image: mehdijebali/crud-front:1.5
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"