apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-pod
  template:
    metadata:
      labels:
        app: front-pod
